/**
 * Knowledge Base definitions for general sustainability queries.
 */
export const SUSTAINABILITY_KB = {
  co2e: "CO2e stands for Carbon Dioxide Equivalent. It is a metric used to compare emissions from various greenhouse gases (like methane and nitrous oxide) based on their global-warming potential, relative to carbon dioxide.",
  footprint: "A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by our individual actions, from energy use, transportation, diets, and consumer shopping.",
  offset: "Carbon offsetting is a mechanism where individuals or companies fund environmental projects (such as tree-planting or wind farms) to balance out their own carbon emissions.",
  recycling: "Recycling prevents materials from going to landfills. Organic materials in landfills undergo anaerobic digestion, which releases methane—a greenhouse gas 28 times more potent than carbon dioxide."
};

/**
 * Generates contextual advice based on category.
 * 
 * @param {string} category - Footprint category
 * @param {Object} context - User context with profile, emissions, recommendations
 * @returns {string} Contextual advice
 */
export function generateAdvice(category, context) {
  const { userProfile, emissionBreakdown } = context;

  switch (category) {
    case 'transport':
      if (userProfile.transport === 'car') {
        return `Your travel footprint is high at ${emissionBreakdown.transportEmission.yearly} kg CO₂e. Switching to a hybrid/EV or swapping two car commutes for public transit represents a high-impact reduction opportunity.`;
      }
      return `Awesome job! Commuting by ${userProfile.transport} keeps your travel footprint at ${emissionBreakdown.transportEmission.yearly} kg CO₂e/year.`;
    case 'food':
      if (userProfile.food === 'heavy_meat' || userProfile.food === 'high meat') {
        return `Switching from a heavy-meat diet (currently ${emissionBreakdown.foodEmission.yearly} kg CO₂e/year) to vegetarian or flexitarian can cut food emissions by 30% to 50%.`;
      }
      return `Your diet choice (${userProfile.food}) keeps food footprint at a low ${emissionBreakdown.foodEmission.yearly} kg CO₂e/year.`;
    default:
      return "Consider reducing energy consumption and purchasing secondhand items to optimize your profile.";
  }
}

/**
 * Explains specific carbon factors.
 * 
 * @param {string} factor - Footprint factor
 * @param {Object} context - User context with emissions
 * @returns {string} Carbon factor explanation
 */
export function generateCarbonExplanation(factor, context) {
  const { emissionBreakdown } = context;
  const yearly = emissionBreakdown.totalEmission.yearly;

  if (factor === 'electricity') {
    const energyVal = emissionBreakdown.energyEmission.yearly;
    const pct = Math.round((energyVal / yearly) * 100);
    return `Your home electricity usage accounts for ${energyVal} kg CO₂e/year (${pct}% of your total). Lowering thermostat temperatures or installing LED bulbs directly reduces this footprint.`;
  }
  return `Your overall emissions are ${yearly} kg CO₂e/year.`;
}

/**
 * Core contextual response generator.
 * 
 * @param {string} query - User chat query
 * @param {Object} context - User context with profile, emissions, recommendations
 * @returns {string} Formatted bot response
 */
export function generateResponse(query, context) {
  const q = query.toLowerCase().trim();
  const { emissionBreakdown, recommendations } = context;
  const yearlyTotal = emissionBreakdown.totalEmission.yearly;

  // 1. Identify Largest Source
  const sources = [
    { name: 'Transportation', val: emissionBreakdown.transportEmission.yearly },
    { name: 'Food Consumption', val: emissionBreakdown.foodEmission.yearly },
    { name: 'Home Electricity', val: emissionBreakdown.energyEmission.yearly },
    { name: 'Shopping Habits', val: emissionBreakdown.shoppingEmission.yearly },
    { name: 'Waste Management', val: emissionBreakdown.wasteEmission.yearly }
  ].sort((a, b) => b.val - a.val);

  const primary = sources[0];

  // 2. Route by Keywords
  if (q.includes('reduce') || q.includes('opportunity') || q.includes('how to cut')) {
    const topRec = recommendations[0];
    if (topRec) {
      return `Based on your profile, your primary reduction opportunity is: "${topRec.recommendation}". Doing so cuts your annual emissions by ${topRec.reductionKg || 'a significant amount'} kg CO₂e (Reasoning: ${topRec.reason}).`;
    }
  }

  if (q.includes('biggest') || q.includes('source') || q.includes('largest') || q.includes('most')) {
    const pct = Math.round((primary.val / yearlyTotal) * 100);
    return `Your biggest source of carbon emissions is ${primary.name}, contributing ${primary.val} kg CO₂e/year (${pct}% of your total footprint).`;
  }

  if (q.includes('public transport') || q.includes('transit') || q.includes('bus') || q.includes('train')) {
    return generateAdvice('transport', context);
  }

  if (q.includes('impact') || q.includes('biggest change') || q.includes('highest score')) {
    const bestRec = recommendations[0];
    if (bestRec) {
      return `The single action with the highest impact score (${bestRec.impactScore}/100) is: "${bestRec.recommendation}". It provides a direct reduction of ${bestRec.reductionKg || 'many'} kg CO₂e/year.`;
    }
  }

  if (q.includes('money') || q.includes('save') || q.includes('cost') || q.includes('financial')) {
    return `Reducing emissions saves money! Lowering electricity limits saves on utility bills (₹7.00/kWh), eating less meat cuts grocery costs by up to 20%, and buying secondhand items saves on consumer purchases.`;
  }

  // 3. Knowledge Base Lookup
  if (q.includes('co2e') || q.includes('carbon equivalent')) {
    return SUSTAINABILITY_KB.co2e;
  }
  if (q.includes('carbon footprint') || q.includes('what is a footprint')) {
    return SUSTAINABILITY_KB.footprint;
  }
  if (q.includes('offset') || q.includes('offsetting')) {
    return SUSTAINABILITY_KB.offset;
  }
  if (q.includes('recycle') || q.includes('compost')) {
    return SUSTAINABILITY_KB.recycling;
  }

  // 4. Default Fallback
  return `I am here to help you navigate your CarbonMind profile. You can ask me about: "What is my biggest carbon source?", "How can I reduce my emissions?", or explain terms like "What is CO2e?"`;
}
